
services:

  frontend:
    build: ./frontend/
    ports:
      - 7999:80

  server:
    build: ./server/
    restart: always
    depends_on:
      - mysql
    ports:
      - 8000:8000

  mysql:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: airtags
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  airtag0:
    build: ./airtag0/
    depends_on:
      - server
      - mysql
    ports:
      - 8001:8001

  airtag1:
    build: ./airtag1/
    depends_on:
      - server
      - mysql
    ports:
      - 8002:8002
      
  airtag2:
    build: ./airtag2/
    depends_on:
      - server
      - mysql
    ports:
      - 8003:8003

