version: '3'
networks:
  dem:
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRESS_USER: webservice
      POSTGRES_PASSWORD: webservice
      POSTGRES_DB: airtags
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - dem
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d airtags -U root"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 5000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - dem

  server:
    build: ./server
    ports:
      - 80:8000
    networks:
      - dem
    depends_on:
      db:
        condition: service_healthy
    command: ["fastapi", "run", "app/main.py", "--port", "80"]
  

  airtag:
    build: ./airtag
    ports:
      - 81:8001
    command: ["fastapi", "run", "app/main.py", "--port", "81"]